### ISSUE TITLE
Add --all flag for a workspace

### ISSUE THREAD

**Issue by Nemo157** [rust-lang-nursery/rust-clippy#1707]
Currently it looks like the only way to run `cargo clippy` on a workspace is to manually run it on each crate. It would be super helpful if the standard `--all` flag were supported for running `clippy` over all crates in the current workspace.

**Comment by crumblingstatue** [comment]
I'd just like to mention that rustfmt (cargo-fmt) implements this, and it even works for virtual workspaces.

Maybe it could be looked at for implementation clues.

**Comment by BenjaminGill-Metaswitch** [comment]
A minimal version of this should be fairly simple - just loop over all packages in the workspace, rather than picking one (https://github.com/rust-lang-nursery/rust-clippy/blob/master/src/main.rs#L268).

That should work (I'll look at submitting a PR in the fortnight, unless anyone objects). However, given that it would be running the builds in serial, it's not going to be very fast. It would be nice to be able to compile the various crates in parallel (like `cargo build --all`), which should (?) speed things up. I don't know how to do this, however.

**Comment by oli-obk** [comment]
This flag exists now (on master, not published yet). I'm leaving this issue open for the parallelization

**Comment by mathstuf** [comment]
The flag does exist, but I'm seeing that if I manually add `warn(lint)` attributes to a dependent crate, it is marked as an unknown lint. Running each crate individually gets around this.

**Comment by kaleidawave** [comment]
I will add that this seems to "fail fast" i.e. if there are clippy errors with an one workspace member, it will not lint other members of the workspace.

Is there a flag to continue on inter dependencies clippy errors? (as they are only linter errors and the others crates should still compile)

**Comment by Jarcho** [comment]
That would need to be a cargo feature. The same thing happens if you deny a rustc lint while running `cargo check`.

**Comment by kaleidawave** [comment]
> That would need to be a cargo feature. The same thing happens if you deny a rustc lint while running `cargo check`.

Is there an open issue over there that I can follow?

**Comment by Jarcho** [comment]
I'm not aware of any particular open issue to follow, but there is probably something similar if you search.
