### ISSUE TITLE
detect passing a reference where a generic expects `Clone`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang-nursery/rust-clippy#1891]
Example:  calling `fn foo<T: Clone>(t: T)` with `foo(&something)`

We need to tread carefully here in the presence of other bounds though.

**Comment by clarcharr** [comment]
I'm having trouble finding an example where this alone would be the error and the code would otherwise work. Usually the usage of the cloned value will cause an error down the line to indicate that the type is wrong.

Do you have any examples?

**Comment by oli-obk** [comment]
Nope ^^, that's why there's a "needs-discussion" label on this issue.

The only example I can think of is `fn foo<T: Clone)(t: T) -> T { t.clone() }` which is pretty riddiculous.

**Comment by clarcharr** [comment]
So I thought about this and I think that the real error isn't calling this with `&something`, but in fact taking a `T: Clone` object by value instead of by reference. If you're consuming a value and requiring that it can be cloned, that *feels* wrong to me.

But again, there could be legitimate use cases; for example, there might be some sort of algorithm that requires having two copies of a list, but because the list is dropped after anyway, the list is taken by value to avoid an unnecessary clone.

So honestly I doubt that this is a necessary lint, or at least in the wrong direction.

**Comment by oli-obk** [comment]
Yea... I didn't think this through too well
