### ISSUE TITLE
Check for conflicting versions in `Cargo.lock`

### ISSUE THREAD

**Issue by ysimonson** [rust-lang-nursery/rust-clippy#2665]
*Proposal:* Add a check for when there are multiple versions of the same dependency in `Cargo.lock`.

*Why:* If the dependency exports structs or traits, this can lead to very confusing compiler error messaging. I now know to watch out for this, but it was definitely something that caught me more than once when ramping up on rust.

*Example situations:*
* You specify one version of dependency `A`, but another dependency `B` specifies a different version of `A`.
* Your dependency `B` specifies one version of `A`, and another dependency `C` specifies another version of `A`.
* You have a bin and lib. The bin depends on the lib. Both the bin and lib share some dependencies. As recommended, you specify a version range for the dependencies in lib, but pin to specific versions for the dependencies in bin. Over time, the versions drift.

Because this would check `Cargo.lock` instead of the code itself, would this fall outside of the scope of clippy? If not / this makes sense to add, I'd be happy to try to contribute this lint, if I can find some example to build off of :)

**Comment by phansch** [comment]
> Because this would check Cargo.lock instead of the code itself, would this fall outside of the scope of clippy?

We do have the [`T-cargo`](https://github.com/rust-lang-nursery/rust-clippy/labels/T-cargo) label but none of the lints have been worked on so far. As far as I can tell there has been no opposition against cargo lints in clippy, so feel free to take the first steps! We could probably put the cargo lints into a new `clippy_cargo` group, too.

> I'd be happy to try to contribute this lint, if I can find some example to build off of :)

Awesome! I think it should be possible using the [`cargo_metadata`](https://docs.rs/cargo_metadata/0.5.4/cargo_metadata/struct.Metadata.html) crate that we already use in an internal lint: [`tests/versioncheck.rs`](https://github.com/rust-lang-nursery/rust-clippy/blob/master/tests/versioncheck.rs).
I haven't used the crate personally, but it looks like you can [get the dependency graph](https://docs.rs/cargo_metadata/0.5.4/cargo_metadata/struct.Metadata.html#structfield.resolve) pretty easily.

cc @oli-obk because I think you're much more familiar with cargo_metadata :)

**Comment by oli-obk** [comment]
Remember to call https://docs.rs/cargo_metadata/0.5.4/cargo_metadata/fn.metadata_deps.html instead of the `metadata` function, otherwise you don't get any info on the dependencies.

I agree that this needs a new lint group.

**Comment by oli-obk** [comment]
I'd just register a regular lint, implement its `check_crate` method and figure out everything from there.

Alternatively you can have a look at how cargo reports errors in the `Cargo.toml`, maybe we can do something similar or reuse their infrastructure?

**Comment by ysimonson** [comment]
That makes sense, thanks @oli-obk! Incoming PR shortly.

**Comment by ysimonson** [comment]
Good to close this issue now that the PR is open?

**Comment by Manishearth** [comment]
No, issues are closed when the PR lands.

**Comment by oli-obk** [comment]
Almost. `addresses #2665` doesn't work, `fixes #2665` is needed
