### ISSUE TITLE
match vertical bar in front

### ISSUE THREAD

**Issue by warlord500** [rust-lang-nursery/rust-clippy#2791]
a small and rather unknown change to rust syntax, now allows | in the front of a match arm.
I am currently writing a lint against this, my hope is that by starting this issue this now, I can get this in the clippy code base fast. 
if you have any helpful hints for implementing this, that would be much appreciated

**Comment by Manishearth** [comment]
It's a recently RFCd piece of syntax, I don't see the reasons to have a lint against it. Unless there's a tangible reason to not use it that has come up since the RFC (e.g. an alternative), or a drastic reversal of community opinion (as evidenced by a style RFC or otherwise), there's no reason to lint against this.

**Comment by warlord500** [comment]
how about reduce readability? confusing to beginners? unnecessary additional complexity for match arm syntax? the actual community doesn't like it?
