### ISSUE TITLE
Justification needed for fn_to_numeric_cast

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rust-clippy#2980]
https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#fn_to_numeric_cast

> ### What it does
>
> Checks for casts of a function pointer to a numeric type except usize.
>
> ### Why is this bad
>
> Casting a function pointer to something other than usize is not a good style.

Justifying a style lint by calling it not good style is not a justification. I know "style" lints can be more difficult to justify than lints that catch what are almost certain to be bugs, but I looked through the "Why is this bad" section of all 81 other style lints present in Clippy 0.0.212 and I believe every other style lint is adequately justified.

I don't disagree with this lint, but by itself this explanation is not something I can point someone to and have them understand why I am asking them to change their code.

Mentioning @VKlayd who worked on this lint in #2814.

**Comment by oli-obk** [comment]
A few points that should be in the "why is this bad" section:

* anything other than usize/isize is not portable across architectures, because you end up losing bits if the target type is too small or end up with a bunch of extra bits that waste space and add more instructions to the final binary than strictly necessary for the problem
* isize is signed, which makes little sense for an address, so usize is preferrable
* pointer sized integers (isize/usize) are the correct type for holding a pointer without any extra type information holding you back.
