### ISSUE TITLE
replace #[cfg_attr(rustfmt, rustfmt_skip)] with #[rustfmt::skip]

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rust-clippy#3121]
It would be nice to have a clippy lint for porting the old rustfmt_skip attribute to the new `rustfmt::skip` one.

**Comment by flip1995** [comment]
I worked on a lint for `cfg_attr(clippy)` before, but failed at inner attributes:
https://github.com/flip1995/rust-clippy/commits/cfg_attr_lint

But since inner attributes aren't really relevant for `cfg_attr(rustfmt)` this code can be used pretty much as it is right now for `rustfmt`. If someone is interested in implementing this, feel free to reuse this code!
