### ISSUE TITLE
x..(y+1) reads better as x...y

### ISSUE THREAD

**Issue by llogiq** [rust-lang-nursery/rust-clippy#329]
Once we have inclusive ranges (which won't be too long; the RFC has recently been accepted), I think we should advise people to use them.

Perhaps we could also check for `x...(y-1)` while we're at it.

**Comment by llogiq** [comment]
We will have to wait on [rust #28237](https://github.com/rust-lang/rust/issues/28237) implementations.

**Comment by frewsxcv** [comment]
Similarly, x...(y-1) reads better as x..y

**Comment by Stebalien** [comment]
@frewsxcv You have to be careful with that; it only applies to integers. `0.0...(y-1.0)` is not `0.0..y`

**Comment by llogiq** [comment]
I have yet to see ranges over anything else but integers, so we may just bail on floats.

OTOH I'm curious: What's the difference between `0.0...(y-1.0)` and `(0.0..y)`?

**Comment by Stebalien** [comment]
The latter includes everything but `y` (e.g. `y-0.00000000000000000000000001`).

**Comment by frewsxcv** [comment]
I'm curious about the justification for making the `Range` operator work on floating point numbers...

**Comment by Manishearth** [comment]
So basically there are two things here, the Range struct and the Range iterator. They're implemented as the same, but as a struct it's useful for specifying ranges, and as an iterator it's ... an iterator.

As far as iterators go there is no difference in the floating point thing. This will be true for most practical uses.

As far as range-as-data goes, of course there is a difference, since it's now a set. However range-as-data doesn't seem to be a common pattern.

**Comment by llogiq** [comment]
> However range-as-data doesn't seem to be a common pattern.

I suspect this will change once someone implements a range set.
